version: "3"
services:
  
  frontend:
    container_name: Front_end
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
  
  backend:
    depends_on: 
      - mongo
    container_name: Back_end
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./api:/usr/src/app


  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: hiringroom
      MONGO_INITDB_ROOT_PASSWORD: admin

    ports:
      - "27017:27017"